var firebaseConfig={apiKey:"AIzaSyDfzyKcnRFl22bv7AZcAMMMpZ54FgKavo8",authDomain:"tour-leader-site.firebaseapp.com",projectId:"tour-leader-site",storageBucket:"tour-leader-site.firebasestorage.app",messagingSenderId:"759437911729",appId:"1:759437911729:web:f5b9e086d35ae66e772490",measurementId:"G-EHPXM4M8TC"};
var LOCATIONS=[{id:"tzrif",name:"צריף בן גוריון",stations:[{id:"tzrif1",name:"מייצג אנימציה, בן גוריון מארח, ביתן 1",capacity:1},{id:"tzrif2",name:"מייצג אנימציה, בן גוריון מארח, ביתן 2",capacity:1},{id:"tzrif3",name:"הבית של בן גוריון",capacity:1},{id:"tzrif4",name:"בית הגבס",capacity:1},{id:"tzrif5",name:"מפה טופוגרפית",capacity:1},{id:"tzrif6",name:"סרטון מנהיגות",capacity:1},{id:"tzrif7",name:"בן גוריון במבחן הזמן",capacity:1},{id:"tzrif8",name:"ספסלים בחוץ, אפשר לשבת על הדשא",capacity:9999}]},{id:"kever",name:"קבר בן גוריון",stations:[{id:"kever1",name:"הקבר",capacity:2},{id:"kever2",name:"הדשא",capacity:9999}]}];
var ALL_STATIONS=[];for(var li=0;li<LOCATIONS.length;li++){for(var si=0;si<LOCATIONS[li].stations.length;si++){var st=LOCATIONS[li].stations[si];ALL_STATIONS.push({id:st.id,name:st.name,capacity:st.capacity,locationId:LOCATIONS[li].id,locationName:LOCATIONS[li].name});}}
var db=null,groups={},messages=[],selectedGroupId=localStorage.getItem("selectedGroupId")||null,timerInterval=null,lastNotificationKey="";
var seenMessageIds=JSON.parse(localStorage.getItem("seenMessageIds")||"{}");
var pendingSave=localStorage.getItem("pendingSave")==="true";
function $(id){return document.getElementById(id);}function setSyncStatus(t){var e=$("syncStatus");if(e)e.textContent=t;}function nowTime(){return new Date().toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"});}
function boot(){try{setSyncStatus("Local mode ready");fillLocationSelectSafe();restoreLeaderInputs();var local=loadLocalState();groups=normalizeGroups(local.groups||{});messages=normalizeMessages(local.messages||[]);if(selectedGroupId&&groups[selectedGroupId])showDashboard(selectedGroupId);renderAll();loadFirebaseScripts();}catch(e){setSyncStatus("Script error: "+e.message);alert("Site script error: "+e.message);}}
function loadFirebaseScripts(){var a=document.createElement("script");a.src="https://www.gstatic.com/firebasejs/8.10.1/firebase-app.js";a.onload=function(){var f=document.createElement("script");f.src="https://www.gstatic.com/firebasejs/8.10.1/firebase-firestore.js";f.onload=initFirebaseSafe;f.onerror=function(){setSyncStatus("Local mode only - Firebase script failed");};document.head.appendChild(f);};a.onerror=function(){setSyncStatus("Local mode only - Firebase script failed");};document.head.appendChild(a);}
function initFirebaseSafe(){try{firebase.initializeApp(firebaseConfig);db=firebase.firestore();setSyncStatus("Connecting to Firebase...");db.collection("tour").doc("state").onSnapshot(function(snap){setSyncStatus("Online sync enabled");var localGroups=groups,localMessages=messages;if(snap.exists){var data=snap.data()||{};var remoteGroups=normalizeGroups(data.groups||{});var remoteMessages=normalizeMessages(data.messages||[]);if(pendingSave&&selectedGroupId&&localGroups[selectedGroupId]){remoteGroups[selectedGroupId]=localGroups[selectedGroupId];remoteMessages=mergeMessages(remoteMessages,localMessages);groups=remoteGroups;messages=remoteMessages;saveLocalState();pushPendingSave();}else{groups=remoteGroups;messages=remoteMessages;saveLocalState();}}else{pendingSave=true;localStorage.setItem("pendingSave","true");pushPendingSave();}renderAll();notifyNewMessagesForMe();},function(err){db=null;setSyncStatus("Firebase error: "+(err.code||err.message));alert("Firebase cannot sync. Check Firestore rules/test mode.");});}catch(e){db=null;setSyncStatus("Firebase error: "+e.message);}}
function mergeMessages(a,b){var seen={},out=[],i;for(i=0;i<a.length;i++){if(!seen[a[i].id]){seen[a[i].id]=true;out.push(a[i]);}}for(i=0;i<b.length;i++){if(!seen[b[i].id]){seen[b[i].id]=true;out.push(b[i]);}}out.sort(function(x,y){return(x.ts||0)-(y.ts||0);});return out.slice(-80);}
function markDirty(){pendingSave=true;localStorage.setItem("pendingSave","true");}function loadLocalState(){try{return JSON.parse(localStorage.getItem("tourState")||"{}");}catch(e){return{};}}function saveLocalState(){localStorage.setItem("tourState",JSON.stringify({groups:groups,messages:messages}));}
function saveAllState(){markDirty();saveLocalState();if(!db){setSyncStatus("Local changes pending sync");return false;}pushPendingSave();return true;}function pushPendingSave(){if(!db)return false;db.collection("tour").doc("state").set({groups:groups,messages:messages},{merge:true}).then(function(){pendingSave=false;localStorage.setItem("pendingSave","false");setSyncStatus("Online sync enabled");}).catch(function(err){pendingSave=true;localStorage.setItem("pendingSave","true");setSyncStatus("Save failed: "+(err.code||err.message));});return true;}
function normalizeGroups(data){var m=data||{};for(var id in m){if(!Object.prototype.hasOwnProperty.call(m,id))continue;var g=m[id]||{};g.name=g.name||id;g.bigGroup=g.bigGroup||(id.indexOf("-B-")>=0?"B":"A");g.status=g.status||"not started";g.lastStatusTime=g.lastStatusTime||"";g.active=normalizeActive(g.active);g.waitingFor=normalizeWaiting(g.waitingFor);g.routePlan=normalizeRoutePlan(g.routePlan||[]);g.planIndex=Number(g.planIndex||0);m[id]=g;}return m;}
function normalizeMessages(a){return(!a||!a.length)?[]:a.slice(-80);}function normalizeWaiting(w){if(!w)return null;var s=getStationInfo(w.stationId||w.stationName);if(!s)return null;return{stationId:s.id,stationName:s.name,locationName:s.locationName,time:w.time||nowTime()};}
function normalizeActive(a){if(!a)return null;var s=getStationInfo(a.stationId||a.station||a.stationName);if(!s)return null;var start=Number(a.startMs||a.startedAt||new Date().getTime());var dur=Number(a.duration||a.durationMinutes||15);return{locationId:s.locationId,locationName:s.locationName,stationId:s.id,stationName:s.name,startMs:start,duration:dur,endMs:start+dur*60000};}
function normalizeRoutePlan(p){var out=[];for(var i=0;i<p.length;i++){var s=getStationInfo(p[i].stationId||p[i].stationName);if(s)out.push({locationId:s.locationId,stationId:s.id,stationName:s.name,duration:Number(p[i].duration||15)});}return out;}
function restoreLeaderInputs(){if($("leaderNameInput"))$("leaderNameInput").value=localStorage.getItem("leaderName")||"";if($("bigGroupSelect"))$("bigGroupSelect").value=localStorage.getItem("bigGroup")||"A";}
function enterLeaderSafe(){try{var name=(($("leaderNameInput")&&$("leaderNameInput").value)||"").trim();var big=(($("bigGroupSelect")&&$("bigGroupSelect").value)||"A");if(!name){alert("Write your leader/team name first.");return;}var id=makeLeaderId(name,big);localStorage.setItem("leaderName",name);localStorage.setItem("bigGroup",big);if(!groups[id])groups[id]={name:name,bigGroup:big,status:"not started",lastStatusTime:"",active:null,waitingFor:null,routePlan:[],planIndex:0,userCreated:true};groups[id].name=name;groups[id].bigGroup=big;groups[id].userCreated=true;selectedGroupId=id;localStorage.setItem("selectedGroupId",id);saveAllState();showDashboard(id);}catch(e){alert("Enter failed: "+e.message);}}
function makeLeaderId(n,b){var h=0,r=String(b)+":"+String(n).trim().toLowerCase();for(var i=0;i<r.length;i++){h=((h<<5)-h)+r.charCodeAt(i);h=h|0;}if(h<0)h=-h;return"leader-"+b+"-"+h;}
function changeLeaderSafe(){selectedGroupId=null;localStorage.removeItem("selectedGroupId");if($("setupCard"))$("setupCard").classList.remove("hidden");if($("dashboard"))$("dashboard").classList.add("hidden");}
function showDashboard(id){selectedGroupId=id;localStorage.setItem("selectedGroupId",id);if($("setupCard"))$("setupCard").classList.add("hidden");if($("dashboard"))$("dashboard").classList.remove("hidden");if($("groupName"))$("groupName").textContent=(groups[id].name||id)+" · Big Group "+(groups[id].bigGroup||"");renderAll();if(timerInterval)clearInterval(timerInterval);timerInterval=setInterval(function(){updateCurrentDisplay();renderOverviewSafe();},1000);}
function fillLocationSelectSafe(){var sel=$("locationSelect");if(!sel)return;sel.innerHTML="";for(var i=0;i<LOCATIONS.length;i++){var o=document.createElement("option");o.value=LOCATIONS[i].id;o.textContent=LOCATIONS[i].name;sel.appendChild(o);}fillStationSelectSafe();}
function fillStationSelectSafe(){var loc=$("locationSelect")?$("locationSelect").value:LOCATIONS[0].id;fillStationSelectElement($("stationSelect"),loc,null);checkLiveCapacitySafe();}
function fillStationSelectElement(sel,locId,selected){if(!sel)return;sel.innerHTML="";var loc=LOCATIONS[0];for(var i=0;i<LOCATIONS.length;i++)if(LOCATIONS[i].id===locId)loc=LOCATIONS[i];for(var j=0;j<loc.stations.length;j++){var o=document.createElement("option");o.value=loc.stations[j].id;o.textContent=loc.stations[j].name;sel.appendChild(o);}if(selected)sel.value=selected;}
function addPlanStepSafe(){if(!selectedGroupId||!groups[selectedGroupId]){alert("Enter your name first.");return;}updatePlanFromUI(false);groups[selectedGroupId].routePlan.push({locationId:"tzrif",stationId:"tzrif1",stationName:"מייצג אנימציה, בן גוריון מארח, ביתן 1",duration:15});renderPlanSafe();}
function removePlanStepSafe(i){if(!selectedGroupId||!groups[selectedGroupId])return;updatePlanFromUI(false);groups[selectedGroupId].routePlan.splice(i,1);renderPlanSafe();}
function renderPlanSafe(){var list=$("routePlanList");if(!list||!selectedGroupId||!groups[selectedGroupId])return;var plan=groups[selectedGroupId].routePlan||[];list.innerHTML="";if(!plan.length){list.innerHTML='<p class="hint">No planned route yet. Press + Add route step.</p>';renderPlanWarningsSafe();return;}for(var i=0;i<plan.length;i++){var row=document.createElement("div");row.className="stop";row.setAttribute("data-i",i);var title=document.createElement("p");title.className="hint";title.textContent="Step "+(i+1);row.appendChild(title);var locLabel=document.createElement("label");locLabel.textContent="Location";var locSel=document.createElement("select");locSel.className="planLocation";locSel.setAttribute("data-i",i);fillPlanLocationSelect(locSel,plan[i].locationId||"tzrif");locSel.onchange=function(){var idx=Number(this.getAttribute("data-i"));var rows=document.querySelectorAll("#routePlanList .stop");fillStationSelectElement(rows[idx].querySelector(".planStation"),this.value,null);updatePlanFromUI(false);renderPlanWarningsSafe();};locLabel.appendChild(locSel);row.appendChild(locLabel);var stLabel=document.createElement("label");stLabel.textContent="Station";var stSel=document.createElement("select");stSel.className="planStation stationInput";fillStationSelectElement(stSel,locSel.value,plan[i].stationId);stSel.onchange=function(){updatePlanFromUI(false);renderPlanWarningsSafe();};stLabel.appendChild(stSel);row.appendChild(stLabel);var durLabel=document.createElement("label");durLabel.textContent="Minutes";var dur=document.createElement("input");dur.className="planDuration";dur.type="number";dur.min="1";dur.max="180";dur.value=plan[i].duration||15;dur.oninput=function(){updatePlanFromUI(false);};durLabel.appendChild(dur);row.appendChild(durLabel);var btn=document.createElement("button");btn.className="ghost";btn.type="button";btn.textContent="Remove";btn.setAttribute("data-i",i);btn.onclick=function(){removePlanStepSafe(Number(this.getAttribute("data-i")));};row.appendChild(btn);list.appendChild(row);}renderPlanWarningsSafe();}
function fillPlanLocationSelect(sel,val){sel.innerHTML="";for(var i=0;i<LOCATIONS.length;i++){var o=document.createElement("option");o.value=LOCATIONS[i].id;o.textContent=LOCATIONS[i].name;sel.appendChild(o);}sel.value=val||"tzrif";}
function updatePlanFromUI(mark){if(!selectedGroupId||!groups[selectedGroupId])return;var rows=document.querySelectorAll("#routePlanList .stop"),plan=[];for(var i=0;i<rows.length;i++){var st=rows[i].querySelector(".planStation").value;var info=getStationInfo(st);if(info)plan.push({locationId:info.locationId,stationId:info.id,stationName:info.name,duration:Number(rows[i].querySelector(".planDuration").value||15)});}groups[selectedGroupId].routePlan=plan;if(mark!==false)markDirty();}
function savePlanSafe(){updatePlanFromUI(true);var c=getPlanConflictsFor(selectedGroupId);if(c.length&&!confirm("Plan conflicts found:\n\n"+c.slice(0,5).join("\n")+"\n\nSave anyway?"))return;var synced=saveAllState();alert(synced?"Planned route saved and syncing.":"Planned route saved on this phone. It will sync when Online sync enabled.");renderAll();}
function loadNextPlanStepSafe(){if(!groups[selectedGroupId])return;var p=groups[selectedGroupId].routePlan||[],idx=Number(groups[selectedGroupId].planIndex||0);if(!p.length){alert("No planned route yet.");return;}if(idx>=p.length)idx=0;var s=getStationInfo(p[idx].stationId);if(!s)return;$("locationSelect").value=s.locationId;fillStationSelectSafe();$("stationSelect").value=s.id;$("durationInput").value=p[idx].duration||15;groups[selectedGroupId].planIndex=idx+1;saveAllState();checkLiveCapacitySafe();alert("Loaded step "+(idx+1)+": "+s.name);}
function getPlanConflictsFor(groupId){var g=groups[groupId],p=g?(g.routePlan||[]):[],out=[];for(var i=0;i<p.length;i++){var s=getStationInfo(p[i].stationId);if(!s||s.capacity>=9999)continue;var count=1,names=[];for(var id in groups){if(!Object.prototype.hasOwnProperty.call(groups,id)||id===groupId)continue;var op=groups[id].routePlan||[];if(op[i]&&op[i].stationId===s.id){count++;names.push(groups[id].name);}}if(count>s.capacity)out.push("Step "+(i+1)+" · "+s.name+" over limit with: "+names.join(", "));}return out;}
function renderPlanWarningsSafe(){var box=$("planWarnings");if(!box||!selectedGroupId)return;var c=getPlanConflictsFor(selectedGroupId);box.innerHTML="";for(var i=0;i<c.length;i++){var p=document.createElement("p");p.className="conflictText";p.textContent=c[i];box.appendChild(p);}}
function startNowSafe(){if(!selectedGroupId||!groups[selectedGroupId]){alert("Enter your name first.");return;}var s=getStationInfo($("stationSelect").value),d=Number($("durationInput").value||15);if(!s)return;var active=getActiveGroupsAtStation(s.id).filter(function(x){return x.id!==selectedGroupId;});if(s.capacity<9999&&active.length>=s.capacity){if(!confirm(s.name+" is already full.\nCurrently there: "+active.map(function(x){return x.group.name;}).join(", ")+"\n\nStart anyway?"))return;}var start=new Date().getTime();groups[selectedGroupId].active={locationId:s.locationId,locationName:s.locationName,stationId:s.id,stationName:s.name,startMs:start,duration:d,endMs:start+d*60000};groups[selectedGroupId].status="active";groups[selectedGroupId].waitingFor=null;groups[selectedGroupId].lastStatusTime=nowTime();var synced=saveAllState();renderAll();alert(synced?"Started and syncing.":"Started only on this phone until Firebase connects.");}
function finishStationSafe(){if(!groups[selectedGroupId])return;var old=groups[selectedGroupId].active?groups[selectedGroupId].active.stationName:"station";groups[selectedGroupId].active=null;groups[selectedGroupId].status="finished early";groups[selectedGroupId].lastStatusTime=nowTime();sendMessageToWaitingForMyStation("free","I finished at "+old+". You can enter now.");var synced=saveAllState();renderAll();alert(synced?"Finished and syncing.":"Finished only on this phone until Firebase connects.");}
function waitingForStationSafe(){if(!groups[selectedGroupId])return;var s=getStationInfo($("stationSelect").value);if(!s)return;groups[selectedGroupId].status="waiting";groups[selectedGroupId].waitingFor={stationId:s.id,stationName:s.name,locationName:s.locationName,time:nowTime()};var holders=getActiveGroupsAtStation(s.id).filter(function(x){return x.id!==selectedGroupId;});if(!holders.length)addMessage("system",selectedGroupId,"No one is marked inside "+s.name+". You may be able to enter.","info",s.id);for(var i=0;i<holders.length;i++)addMessage(selectedGroupId,holders[i].id,groups[selectedGroupId].name+" is waiting for "+s.name+".","waiting",s.id);var synced=saveAllState();renderAll();alert(synced?"Waiting message syncing.":"Waiting saved only on this phone until Firebase connects.");}
function delayedHereSafe(){if(!groups[selectedGroupId])return;groups[selectedGroupId].status="delayed";groups[selectedGroupId].lastStatusTime=nowTime();var sent=sendMessageToWaitingForMyStation("delayed",groups[selectedGroupId].name+" is delayed at this station.");var synced=saveAllState();renderAll();alert(sent?(synced?"Delay syncing to waiting leaders.":"Delay saved only on this phone until Firebase connects."):"No waiting leaders found. Delay status saved.");}
function generalDelayedSafe(){if(!groups[selectedGroupId])return;groups[selectedGroupId].status="delayed";groups[selectedGroupId].lastStatusTime=nowTime();var synced=saveAllState();renderAll();alert(synced?"General delay syncing.":"General delay saved only on this phone until Firebase connects.");}
function sendMessageToWaitingForMyStation(type,text){if(!groups[selectedGroupId]||!groups[selectedGroupId].active)return 0;var sid=groups[selectedGroupId].active.stationId,sent=0;for(var id in groups){if(Object.prototype.hasOwnProperty.call(groups,id)&&id!==selectedGroupId&&groups[id].waitingFor&&groups[id].waitingFor.stationId===sid){addMessage(selectedGroupId,id,text,type,sid);sent++;}}return sent;}
function addMessage(from,to,text,type,sid){messages.push({id:"m"+new Date().getTime()+"-"+Math.floor(Math.random()*100000),fromId:from,fromName:groups[from]?groups[from].name:"System",toId:to,text:text,type:type||"info",stationId:sid||"",time:nowTime(),ts:new Date().getTime()});messages=messages.slice(-80);}
function renderAll(){updateCurrentDisplay();checkLiveCapacitySafe();renderOverviewSafe();renderMessagesSafe();renderPlanSafe();}
function updateCurrentDisplay(){if(!selectedGroupId||!groups[selectedGroupId])return;var a=groups[selectedGroupId].active;if(!a){$("currentStation").textContent=groups[selectedGroupId].waitingFor?"Waiting for: "+groups[selectedGroupId].waitingFor.stationName:"Not started";$("timeLeft").textContent="--:--";$("currentWindow").textContent="Choose a station and press Start now, or press Waiting.";$("nextStation").textContent=groups[selectedGroupId].waitingFor?"Location: "+groups[selectedGroupId].waitingFor.locationName:"Location: -";return;}var left=Math.max(0,Math.round((a.endMs-new Date().getTime())/1000));$("currentStation").textContent=a.stationName;$("timeLeft").textContent=formatSeconds(left);$("currentWindow").textContent=a.duration+" minutes · started "+new Date(a.startMs).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"});$("nextStation").textContent="Location: "+a.locationName;if(left===0){$("timeLeft").classList.add("alertDone");maybeNotify("Station time finished","Press Finish or choose the next station.");}else $("timeLeft").classList.remove("alertDone");}
function checkLiveCapacitySafe(){var w=$("capacityWarning");if(!w||!$("stationSelect"))return;var s=getStationInfo($("stationSelect").value);w.classList.add("hidden");w.textContent="";if(!s||s.capacity>=9999)return;var a=getActiveGroupsAtStation(s.id).filter(function(x){return x.id!==selectedGroupId;});if(a.length>=s.capacity){w.classList.remove("hidden");w.textContent="Full now: "+a.map(function(x){return x.group.name;}).join(", ")+" already at this station.";}else if(a.length>0){w.classList.remove("hidden");w.textContent="Currently there: "+a.map(function(x){return x.group.name;}).join(", ")+". Capacity: "+s.capacity+".";}}
function renderMessagesSafe(){var box=$("messagesBox");if(!box||!selectedGroupId)return;box.innerHTML="";var mine=[];for(var i=messages.length-1;i>=0;i--)if(messages[i].toId===selectedGroupId)mine.push(messages[i]);if(!mine.length){box.innerHTML='<p class="hint">No messages.</p>';return;}for(var j=0;j<mine.length&&j<12;j++){var m=mine[j],d=document.createElement("div");d.className="stationBox"+(m.type==="waiting"?" over":"");d.innerHTML='<div class="stationTitle"><span>'+escapeHtml(m.fromName||"Message")+'</span><span>'+escapeHtml(m.time||"")+'</span></div><p>'+escapeHtml(m.text)+'</p>';box.appendChild(d);}}
function renderOverviewSafe(){var c=$("stationsOverview");if(!c)return;var by={},wait={};for(var i=0;i<ALL_STATIONS.length;i++){by[ALL_STATIONS[i].id]=[];wait[ALL_STATIONS[i].id]=[];}var idle=[];for(var id in groups){if(!Object.prototype.hasOwnProperty.call(groups,id))continue;var g=groups[id];if(g.active){by[g.active.stationId].push({id:id,group:g});}else if(g.waitingFor){wait[g.waitingFor.stationId].push({id:id,group:g});}else idle.push({id:id,group:g});}c.innerHTML="";for(var l=0;l<LOCATIONS.length;l++){var h=document.createElement("h3");h.textContent=LOCATIONS[l].name;h.dir="rtl";c.appendChild(h);for(var st=0;st<LOCATIONS[l].stations.length;st++){var s=LOCATIONS[l].stations[st],list=by[s.id]||[],ws=wait[s.id]||[],box=document.createElement("div");box.className="stationBox"+(s.capacity<9999&&list.length>s.capacity?" over":"");box.innerHTML='<div class="stationTitle"><span dir="rtl">'+escapeHtml(s.name)+'</span><span>'+list.length+' inside · '+ws.length+' waiting · '+(s.capacity>=9999?'no limit':'limit '+s.capacity)+'</span></div>';for(var p=0;p<list.length;p++){var pill=document.createElement("span"),gg=list[p].group,left=gg.active?Math.max(0,Math.round((gg.active.endMs-new Date().getTime())/1000)):0;pill.className="groupPill"+(gg.status==="delayed"?" delayed":"");pill.textContent=gg.name+" ("+(gg.bigGroup||"")+") - inside - "+formatSeconds(left);box.appendChild(pill);}for(var q=0;q<ws.length;q++){var wp=document.createElement("span"),wg=ws[q].group;wp.className="groupPill waiting";wp.textContent=wg.name+" ("+(wg.bigGroup||"")+") - waiting";box.appendChild(wp);}c.appendChild(box);}}var ib=document.createElement("div");ib.className="stationBox";ib.innerHTML='<div class="stationTitle"><span>Not started / finished</span><span>'+idle.length+' leaders</span></div>';for(var k=0;k<idle.length;k++){var ip=document.createElement("span");ip.className="groupPill";ip.textContent=idle[k].group.name+" ("+(idle[k].group.bigGroup||"")+") - "+(idle[k].group.status||"not started");ib.appendChild(ip);}c.appendChild(ib);}
function notifyNewMessagesForMe(){if(!selectedGroupId)return;for(var i=0;i<messages.length;i++){var m=messages[i];if(m.toId===selectedGroupId&&!seenMessageIds[m.id]){seenMessageIds[m.id]=true;localStorage.setItem("seenMessageIds",JSON.stringify(seenMessageIds));maybeNotify("Tour message",m.text);}}}
function getActiveGroupsAtStation(id){var a=[];for(var g in groups)if(Object.prototype.hasOwnProperty.call(groups,g)&&groups[g].active&&groups[g].active.stationId===id)a.push({id:g,group:groups[g]});return a;}function getStationInfo(v){if(!v)return null;var n=v==="ספסלים בחוץ, אפשר לשבת על הדשה"?"ספסלים בחוץ, אפשר לשבת על הדשא":v;for(var i=0;i<ALL_STATIONS.length;i++)if(ALL_STATIONS[i].id===n||ALL_STATIONS[i].name===n)return ALL_STATIONS[i];return null;}
function formatSeconds(sec){var m=Math.floor(sec/60),s=sec%60;return(m<10?"0"+m:String(m))+":"+(s<10?"0"+s:String(s));}function requestNotificationsSafe(){if(!("Notification"in window)){alert("Notifications are not supported on this phone/browser.");return;}Notification.requestPermission().then(function(p){alert(p==="granted"?"Alerts enabled.":"Alerts were not allowed.");});}function maybeNotify(t,b){var k=t+b+new Date().toISOString().slice(0,16);if(lastNotificationKey===k)return;lastNotificationKey=k;if("Notification"in window&&Notification.permission==="granted")new Notification(t,{body:b});if(navigator.vibrate)navigator.vibrate([250,120,250]);}function escapeHtml(str){return String(str).replace(/[&<>\"]/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c];});}
boot();